{% set name = "pysolr" %}
{% set version = "3.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 88ecb176627db6bcf9aeb94a3570bfa0363cb68be4b2a6d89a957d4a87c0a81b

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - requests >=2.9.1
    - setuptools

test:
  imports:
    - pysolr

about:
  home: https://github.com/django-haystack/pysolr/
  license: BSD 3-clause
  summary: 'Lightweight python wrapper for Apache Solr.'
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cehbrecht
