travis:
  secure:
    BINSTAR_TOKEN: f3joqLx++nrEKV9NUHrN0mc86oRfQR7YR33W4tw5mnfVystaVZ/zNWuZXp8pyhtwclNXC4od2f/wLt9mjn1WpSh2w+VF+mlzanlOwLpqAl+riKaGECqcdCPV8gY2kg/yhB8jDAqfz3mKKiXoi5Ci9DBB1XV0SuX3GuUP9SC+ABxAsVYGlVvuG4e4cX3Xmy3XbWQiTsY9cims58NAKWqx0ZbFnfb53VFMrL5/6iLEJUAFJyizXjG7wFLy0lUjce3bGTRNfcAsJwMf1uhSJW1u8+jvjjL9RwtASwJjhSBxx6YgX1VzeQIa3l53ZyCGxowZuNuHbh8YEn8872Qdl1ZJ8sxyHaqm3vDcla8h74vqACI0njzlePtK8iEA+wfu3kYZyLC14B7lThAIl+DEGW7W1I+Gpf14Ovww8UNx09N6GApzg67E/9IlF2rr9cXyCnGGWnrDGRw6EmlvUbGC4M56o07FQfOzeh4/LxL0nl4G4y5o83Y0iHsv4QtSyOzLUoBZcZverHFCXKFkbh6RMstZ38oikBjR2ji8PpTNRPdfTrqOZZE9QOiCOw471MUYH9aqABluSc4gi9nLBlvAme3a2m608RXY54x1ax5sNRXi3pQJJMWtTSrGBk16cYXTzeNLRtuVa1VLWu1WCgTk5UC2SwqfEID60ifXCXR+jq4AXuw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
