travis:
  secure:
    BINSTAR_TOKEN: reWlJEgNJTWIEX4uXbbmuBvgE2S7yOQLFYWJjFSjmdAxngF9w7o85h9ZuJgcqy1zQ1C5lUbc7ynLi/JDqpcgCg5jXxgJXgx/7uz6FrBxcWC/e/1dUFkdPvp2Ui1O3Vi+C74z3bImp/Wm6d1bAHduvT1ZuITIAVJiTW1p8HYVHGL6/KjNQBvB7G9OXam050JDtOGnst3vjnvBr9b4AZwAMSLCjc6HXn1oX7nWq48wVh3nVtAiAiuIgLV4m+qnAS1gG4Fw0NoM46yr+A1sq9DQaxK5PP9nMLeGO1ZYWuNJJIm6BPrJWV6sjMvVEJGtbufrKIj/RVYX01GcLWDPEt15cwKl8/VC7kUTv87FFsMAfmmAuVjt5DbLhfuQflpKRCkDl4WttMMWJu2CAnL+WZEBVYBcYBUc+xEZzTEjGEwfCUTly35E4YFH/NbWavv26dzXEPQVp1xzI5TK3TU4/Varwk66wWeByYYsO57vo4H8nXj84rRfnZLU3Ix3kxDqFNRQ04RwdgFaROu8FTDarM1r60jtZ8nCFNm3LiOFws21MMSzyrXLYJNSVFT6KCXdtkjqbD4ZXu1DnsCZ4Se+KREkEuRK0veOz8eSfjn7fNSTMV6FweAS5ZV2HsDJwbbGmIRsSF0DGRnMDYPG/POOEXmerc1i+qkTILR6LLoXnS0HIBI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
