travis:
  secure:
    BINSTAR_TOKEN: IRCcZg++P+sTRmNFiDW0/sJEqJfjPcrJswatCB2HfBku2EE3DwszOG9y4QvdoCAQx+iqw/MDxLraOAjOGyjgJgny7ZgPMDqd9V6nXkm9nnGzpd0TmAZLYixz1Ph/EYK6fzBZMCkzuCGlNTNANC8m6IWqik76+Nkfvkaoj/fVb5zvrvfhzPGFM3kNI9tFPkvjmjQXt9j1bnd3nUgQGFE3MgCBHYKwaH8m1VAqpXcXqN/zCUBp4OqQnkSZbF/NPrk+QR8takRHEUOIqYAAEIJqr1y3rmXrtX17CNLJxhsqRSULbazoKNAZvRAiVxaF6fUNWi2BWe/VG2Z4dl4cqp/rbR+J+HR5lw1OF7SNDS4FYYtbyJ92CpUKcXhFBQAqxgb936n0mMqEMQfNEnykaif+TwcT64YU1FEF5sS5SVNeJR5l3Dbt0y3Y0gPzJV071iq9IYn9h2nEzfkZfdbjbEjnslIj/sH10n0uPh1cKM8zd3cv9C73kAzr6+ok1P5Ms6bMmW/YInPYyMBMiB6S0DGcWRWd3gaJtVpoQCoa0fFIBA0twkXn+2FnDve1VLJJI1jZLMT68Mj7GzA8H+3mUdlsLweyoP14AOoNi1Ntlh6j4St+hn2AnD7vRmQCIpfAOj7lD/L7olT+Y4WSI1aR6OeFDBmLLUG5vIOp52aVhYEzOoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
